// These are for the slider function
var numberOfCharacter = document.getElementById("numberOfCharacters");
var numberRange = document.getElementById("numberRange");

//These are the definitions the function pulls its characters from. 
var upperCaseLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
var hasUpperCaseLetters = upperCaseLetters.split("");

var numbers = "1234567890";
var hasNumbers = numbers.split("");

var specialSymbols = "!@#$%^&*()[]{]<>?";
var hasSpecialSymbols = specialSymbols.split("");

var characterLength = "";



// This connects the slider and the number selector together and allows the input to be pulled
//into the password construction.  FUNCTIONAL. 
numberOfCharacters.addEventListener('input', syncSlider);
numberRange.addEventListener('input', syncSlider);

function syncSlider(event) {
  var slider = event.target.value
  numberOfCharacter.value = slider
  numberRange.value = slider
 return slider
}

// This links the button on the HTML page with the ID of "generate" and attaches it to the event listener at the end
// allowing the click to function. 

 var generateBtn = document.querySelector("#generate");

function generatePassword() { 
  // This is where we pull in the value generated by the slider/number selector. 
    const valueOfSliderInput = document.getElementById("numberOfCharacters").value;
  // Pulling the checked/not checked user input from the HTML page. 
    const uppercaseCheck = document.getElementById("uppercase").checked
    const numbersCheck = document.getElementById("numbers").checked
    const symbolsCheck = document.getElementById("symbols").checked

    let password = ""
    let allOfIt = []
  // The 'if' statements that go into effect only if the box has been checked. 
    if (uppercaseCheck) {
        allOfIt = [...allOfIt, ...hasUpperCaseLetters]
        
      
    }
    if (numbersCheck) {
        allOfIt = [...allOfIt, ...hasNumbers]
        
    }
    if (symbolsCheck) {
        allOfIt = [...allOfIt, ...hasSpecialSymbols]
        
    }
    // Prevents a user from generating a non-complex password.  You have to choose an option to meet password criteria. 
    if (allOfIt.length == 0) {
      var passwordTextBoxValue = document.querySelector("#password");
          passwordTextBoxValue.innerHTML = "select at least one box to generate a password"
    } 
    // The random generator. 
    else {
    for (var i = 0; i < valueOfSliderInput; i++) {
    var randomNumber = Math.floor(Math.random() * allOfIt.length);
    password += allOfIt[randomNumber];
    
  }
  // Print the generated string in the text box with the id "password"
  var passwordTextBox = document.querySelector("#password");
  passwordTextBox.value = password;
}
}
// The event listner that makes the button click. 
generateBtn.addEventListener("click", generatePassword); 
